export const name = "calcs";

export const add = (a: number, b: number) => a + b;
export const subtract = (a: number, b: number) => a - b;
export const multiply = (a: number, b: number) => a * b;
export const divide = (a: number, b: number) => a / b;
export const square = (a: number) => a * a;
export const squareRoot = (a: number) => Math.sqrt(a);
export const cube = (a: number) => a * a * a;
export const cubeRoot = (a: number) => Math.cbrt(a);
export const power = (a: number, b: number) => Math.pow(a, b);
export const log = (a: number) => Math.log(a);
export const log10 = (a: number) => Math.log10(a);
export const log2 = (a: number) => Math.log2(a);
export const sin = (a: number) => Math.sin(a);
export const cos = (a: number) => Math.cos(a);
export const tan = (a: number) => Math.tan(a);
export const asin = (a: number) => Math.asin(a);
export const acos = (a: number) => Math.acos(a);
export const atan = (a: number) => Math.atan(a);
